DROP TABLE FINAL_CHAT;
DROP SEQUENCE CHAT_SEQ;

CREATE SEQUENCE CHAT_SEQ;

CREATE TABLE FINAL_CHAT(
	NUM NUMBER PRIMARY KEY,
	NAME VARCHAR2(200),
	PWD VARCHAR2(200),
	TOTALCOUNT NUMBER,
	REMAINCOUNT NUMBER,
	MASTER VARCHAR2(50),
	USER1 VARCHAR2(50),
	USER2 VARCHAR2(50),
	USER3 VARCHAR2(50),
	USER4 VARCHAR2(50),
	USER5 VARCHAR2(50),
	USER6 VARCHAR2(50),
	CONTENT VARCHAR2(200)
);

SELECT * FROM FINAL_CHAT;

DROP TABLE FINAL_CHATMEMBER;
DROP SEQUENCE CHAT_MEMBER_SEQ;

CREATE SEQUENCE CHAT_MEMBER_SEQ;

CREATE TABLE FINAL_CHATMEMBER(
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(200),
	ROOM VARCHAR2(200),
	PRIROOM VARCHAR2(200)
);

SELECT * FROM FINAL_CHATMEMBER;